print("*************************************************************************")
print("Write a program to display value, type & memory address of a variable")
print("*************************************************************************")

name = (input("Enter a value of variable name: "))
print("************************************************")
print("Value of variable name is:", name)
print("Type of variable name is:", type(name))
print("Memory address of variable name is:", id(name))
print("************************************************") 

age = int(input("Enter a value of variable age: "))
print("************************************************")
print("Value of variable age is:", age)
print("Type of variable age is:", type(age))
print("Memory address of variable age is:", id(age)) 
print("************************************************") 