import sys
import os
import time
from proc_info import process_scanner
import smtplib
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

# Email Configuration 
SENDER_EMAIL = "anis.pythondev2320@gmail.com"
APP_PWD = "khmq zzbb vlef nten"
SUBJECT = "Operating System Process Surveillance Report"+"_%s"%time.strftime("%Y:%m:%d_%I-%M-%S %p")
BODY = """
Hello,
Please find the attached log file generated by the system.

Regards,
Anis Madarkhan
    """
PORT = 465

BORDER = "-" * 60

def send_log_report_to_mail(log_file):
    if not os.path.exists(log_file):
        print(f"Error: Log file '{log_file}' not found.")
        return
    
    # Step 1: Create Email Object
    msg_obj = MIMEMultipart()

    # Step 2: Set mail headers
    msg_obj["From"] = SENDER_EMAIL
    msg_obj["to"] = sys.argv[2]
    msg_obj["Subject"] = SUBJECT

    # Step 3: Add mail body
    msg_obj.attach(MIMEText(BODY, "plain"))

    attachment_object = open(log_file, "rb")
    part = MIMEApplication(attachment_object.read(), Name = os.path.basename(log_file))
    part["Content-Disposition"] = f'attachment; filename="{os.path.basename(log_file)}"'
    msg_obj.attach(part)
    
    try:
        # Step 4: Create SMTP SSL connection manually
        smtp_obj = smtplib.SMTP_SSL("smtp.gmail.com", PORT)

        # Step 5: Login using Gmail & App Password
        smtp_obj.login(SENDER_EMAIL, APP_PWD)

        # Step 6: Send the email
        smtp_obj.send_message(msg_obj)

        # Step 7: Close connection manually
        smtp_obj.quit()

        print("The log report through email has been sent successfully.")
        
    except ConnectionError as ce_obj:
        print(f"Failed to send the email: {ce_obj}")

def log_processes_info(folder_name):
    if os.path.exists(folder_name):
        if not os.path.isdir(folder_name):
            print("Unable to proceed as folder name is existing but its not a directory.")
            sys.exit(1)
    else:
        os.mkdir(folder_name)
        print("Directory for the log file gets created successfully.")

    time_stamp = time.strftime("%Y-%m-%d_%H-%M-%S")
    file_name = os.path.join(folder_name, "Assignment34_Q4_%s.txt" %time_stamp)

    fio_obj = open(file_name, "w")
    
    print(f"Log file gets successfully created with name {file_name}")

    fio_obj.write(BORDER+"\n")
    fio_obj.write("----- Marvellous Platform Surveillance System ----- \n")
    fio_obj.write("Log files gets created at: "+time_stamp+"\n")
    fio_obj.write("Email Sent By: "+SENDER_EMAIL+"\n")
    fio_obj.write("Email Sent To: "+sys.argv[2]+"\n")
    fio_obj.write(BORDER+"\n\n")
    fio_obj.write("------------------- System report -----------------\n")

    # Process Log
    process_data = process_scanner()

    for process in process_data:
        fio_obj.write("PID : %s\n" %process.get("pid"))
        fio_obj.write("Name : %s\n" %process.get("name"))
        fio_obj.write("Username : %s\n" %process.get("username"))
        fio_obj.write("Status : %s\n" %process.get("status"))
        fio_obj.write(BORDER+"\n")

    fio_obj.write(BORDER+"\n")
    fio_obj.write("------------------ End of Log File -----------------\n")
    fio_obj.write(BORDER+"\n")
    fio_obj.close()

    send_log_report_to_mail(file_name)

def main():
    print(BORDER)
    print("----- Marvellous Platform Surveillance System ----- ")
    print(BORDER)

    if len(sys.argv) == 2:
        if sys.argv[1] == "--h" or sys.argv[1] == "--H":
            print("This automation script is use to perfom\n"
                  "1 : It fetch the information of running processess.\n"
                  "2 : It gets auto scheduled periodically.\n"
                  "3 : It maintain all records into log file.\n")
            
        elif sys.argv[1] == "--u" or sys.argv[1] == "--U":
            print("Use the automation script as :\n"
                  f"python {sys.argv[0]} folder_name receiver_email_id\n"                  
                  "folder_name : Name of folder for log file creation.\n"
                  "receiver_email_id : Log file to be sent on the Email Id.")
        else:
            print("Unable to proceed as ther is no matching argument")
            print("Please use --h or --u flag for getting more information")

    elif len(sys.argv) == 3:
        log_processes_info(sys.argv[1])

    else:
        print("Invalid number of arguments")
        print("Unable to proceed as arguments are not matching")
        print("Please use --h or --u flag for getting more information")
    
    print(BORDER)
    print("---- Thank you for using our automation System ----")
    print(BORDER)

if __name__ == "__main__":
    main()