import sys
import os
import hashlib
import schedule
import time
import smtplib
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

# Email Configuration 
SENDER_EMAIL = "anis.pythondev2320@gmail.com"
APP_PWD = "khmq zzbb vlef nten"
RECEIVER_EMAIL = "marvellousinfosystem@gmail.com"
SUBJECT = "Duplicate files deletion report"+"_%s"%time.strftime("%Y:%m:%d_%I-%M-%S %p")
BODY = """
Hello,
Please find the attached log file generated by the system.

Regards,
Anis Madarkhan
    """
PORT = 465

BORDER = "-" * 100

start_time = None

def calculate_checksum(file_name):
    f_obj = open(file_name, "rb")

    h_obj = hashlib.md5()
    buffer = f_obj.read(1024)

    while len(buffer) > 0:
        h_obj.update(buffer)
        buffer = f_obj.read(1024)

    f_obj.close()

    return h_obj.hexdigest()

def find_duplicate(directory_name):
    if not os.path.exists(directory_name):
        print("Error: Path is invalid")
        sys.exit(1)
    
    if not os.path.isdir(directory_name):
        print(f"Error: {directory_name} is not a directory")
        sys.exit(1)

    duplicate = dict()

    for folder_name, sub_folders, file_names in os.walk(directory_name):
        for f_name in file_names:
            f_name = os.path.join(folder_name, f_name)
            check_sum = calculate_checksum(f_name)

            if check_sum in duplicate:
                duplicate[check_sum].append(f_name)
            else:
                duplicate[check_sum] = [f_name]

    return duplicate

def send_log_report_to_mail(log_file):
    if not os.path.exists(log_file):
        print(f"Error: Log file '{log_file}' not found.")
        return
    
    # Step 1: Create Email Object
    msg_obj = MIMEMultipart()

    # Step 2: Set mail headers
    msg_obj["From"] = SENDER_EMAIL
    msg_obj["to"] = RECEIVER_EMAIL
    msg_obj["Subject"] = SUBJECT

    # Step 3: Add mail body
    msg_obj.attach(MIMEText(BODY, "plain"))

    attachment_object = open(log_file, "rb")
    part = MIMEApplication(attachment_object.read(), Name = os.path.basename(log_file))
    part["Content-Disposition"] = f'attachment; filename="{os.path.basename(log_file)}"'
    msg_obj.attach(part)
    
    try:
        # Step 4: Create SMTP SSL connection manually
        smtp_obj = smtplib.SMTP_SSL("smtp.gmail.com", PORT)

        # Step 5: Login using Gmail & App Password
        smtp_obj.login(SENDER_EMAIL, APP_PWD)

        # Step 6: Send the email
        smtp_obj.send_message(msg_obj)

        # Step 7: Close connection manually
        smtp_obj.quit()

        print("The log report through email has been sent successfully.")
        
    except ConnectionError as ce_obj:
        print(f"Failed to send the email: {ce_obj}")

def generate_log_report(log_files_folder_name, directory_name, scanned_files, 
                        check_sum_list, deleted_file_path_list, duplicate_files_count, 
                        start_time, end_time):

    if os.path.exists(log_files_folder_name):
        if not os.path.isdir(log_files_folder_name):
            print("Unable to proceed as folder name is existing but its not a directory.")
            sys.exit(1)
    else:
        os.mkdir(log_files_folder_name)
        print("Directory for the log file gets created successfully.")
        
    time_stamp = time.strftime("%Y-%m-%d_%H-%M-%S")
    file_name = os.path.join(log_files_folder_name, "DuplicateFileDeletionStatusLog_%s.txt" %time_stamp)

    fio_obj = open(file_name, "w")

    fio_obj.write(BORDER+"\n")
    fio_obj.write("-------------- Marvellous Automated Removal of Duplicate Files Application Log Report -------------- \n")
    fio_obj.write("Log files gets created at: "+time_stamp+"\n")
    fio_obj.write(BORDER+"\n")
    fio_obj.write(f"Starting time of directory scan: {start_time}.\n")
    fio_obj.write(f"Completion time of directory scan: {end_time}.\n")
    fio_obj.write(f"Name of the directory scanned: {directory_name}\n")
    fio_obj.write(f"Total number of files scanned: {len(scanned_files)}\n")
    fio_obj.write(f"Total number of duplicate files found: {duplicate_files_count}\n")
    fio_obj.write(f"Total number of duplicate files deleted: {duplicate_files_count}\n")
    fio_obj.write("Complete path of all duplicate files:\n")
    for path in deleted_file_path_list:
        fio_obj.write(path+"\n")

    fio_obj.write("Deleted files checksum values:\n")
    for checksum in check_sum_list:
        fio_obj.write(checksum+"\n")

    fio_obj.write(BORDER+"\n")
    fio_obj.write("------------------------------------------ End of Log Report ---------------------------------------\n")
    fio_obj.write(BORDER+"\n")
    fio_obj.close()

    send_log_report_to_mail(file_name)

def delete_duplicate(directory_name):
    global start_time

    unfiltered_dict = find_duplicate(directory_name)
    duplicate_files_dict = list(filter(lambda x: len(x) > 1, unfiltered_dict.values()))

    count = 0
    total_deleted = 0
    check_sum_list = list()
    deleted_file_path_list = list()
    scanned_files_list = list()

    for folder_name, sub_folders, file_names in os.walk(directory_name):
        for f_name in file_names:
            f_name = os.path.join(folder_name, f_name)
            scanned_files_list.append(f_name)

    for duplicate_files in duplicate_files_dict:
        for duplicate_file in duplicate_files:
            count += 1
            if count > 1:
                check_sum_list.append(calculate_checksum(duplicate_file))
                deleted_file_path_list.append(os.path.abspath(duplicate_file))
                os.remove(duplicate_file)
                total_deleted += 1
        count = 0

    end_time = time.strftime("%I:%M:%S %p")

    generate_log_report("MarvellousDuplicateRemoval", directory_name, scanned_files_list,
                        check_sum_list, deleted_file_path_list, total_deleted, 
                        start_time, end_time)
            
def main():
    global BORDER
    global start_time

    print(BORDER)
    print("----- Marvellous Automated Removal of Duplicate Files Application ----- ")
    print(BORDER)

    # --h & --u handling
    if len(sys.argv) == 2:
        if sys.argv[1] == "--h" or sys.argv[1] == "--H":
            print("This automation script is use to perfom\n"
                  "1 : It checks the duplicate files from the given directory.\n"
                  "2 : It compares the files & deletes any one file which is duplicate.\n"
                  "3 : It gets auto scheduled periodically.\n"
                  "4 : It maintain all records into log file.\n"
                  "5 : It sends log file through mail periodically.")
            
        elif sys.argv[1] == "--u" or sys.argv[1] == "--U":
            print("Use the automation script as :\n"
                  f"python {sys.argv[0]} time_interval folder_name\n"
                  "time_interval : Time in hour for periodic execution.\n"
                  "folder_name : Name of folder for log file creation.")
        else:
            print("Unable to proceed as there is no matching argument")
            print("Please use --h or --u flag for getting more information")

    # Actual Project code
    elif len(sys.argv) == 3:
        # start_time = time.strftime("%I:%M:%S %p")
        # delete_duplicate(sys.argv[2])
        try:
            start_time = time.strftime("%I:%M:%S %p")
            print("Scheduler started successfully")
            print("Press Ctrl + C to abort the automation script")
            schedule.every(int(sys.argv[1])).minutes.do(delete_duplicate, sys.argv[2])

            while True:
                schedule.run_pending()
                time.sleep(1)

        except KeyboardInterrupt:
            sys.exit(1)

    else:
        print("Invalid number of arguments")
        print("Unable to proceed as arguments are not matching")
        print("Please use --h or --u flag for getting more information")
    
    print(BORDER)
    print("-------------- Thank you for using our automation System ---------------")
    print(BORDER)
    
if __name__ == "__main__":
    main()